using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Ascendia.Data;
using Ascendia.Models;
using Ascendia.Services;
using System;
using System.IO;
using System.Threading.Tasks;

namespace Ascendia.Pages
{
    public class EnrollFormModel : PageModel
    {
        private const long MaxUploadBytes = 10 * 1024 * 1024;
        private static readonly HashSet<string> AllowedDocumentExtensions = new(StringComparer.OrdinalIgnoreCase)
        {
            ".pdf", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp"
        };

        private readonly IWebHostEnvironment _environment;
        private readonly AppDbContext _dbContext;
        private readonly StudentNumberService _studentNumberService;

        public EnrollFormModel(
            IWebHostEnvironment environment,
            AppDbContext dbContext,
            StudentNumberService studentNumberService)
        {
            _environment = environment;
            _dbContext = dbContext;
            _studentNumberService = studentNumberService;
        }

        [BindProperty]
        public Student Student { get; set; } = new Student();

        [BindProperty]
        public string? SelectedCourseCode { get; set; }

        public AcademicCourse? SelectedCourse { get; private set; }

        [BindProperty]
        public IFormFile? ProfilePicture { get; set; }

        [BindProperty]
        public IFormFile? PsaBirthCertificate { get; set; }

        [BindProperty]
        public IFormFile? Form138 { get; set; }

        [BindProperty]
        public IFormFile? Form137 { get; set; }

        [BindProperty]
        public IFormFile? GoodMoral { get; set; }

        [BindProperty]
        public IFormFile? Tor { get; set; }

        [BindProperty]
        public IFormFile? PaymentReceipt { get; set; }

        [TempData]
        public string? SuccessMessage { get; set; }

        public async Task OnGetAsync(string? course)
        {
            Student ??= new Student();
            SelectedCourseCode = course?.Trim();
            if (string.IsNullOrWhiteSpace(SelectedCourseCode))
            {
                return;
            }

            await LoadSelectedCourseAsync();
            if (SelectedCourse is not null)
            {
                ApplySelectedCourse();
            }

            Student.StudentNumber = await _studentNumberService.GenerateUniqueAsync(
                HttpContext.RequestAborted);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (Student is null)
            {
                ModelState.AddModelError(string.Empty, "Hindi valid ang enrollment form.");
                return Page();
            }

            Student.StudentType = Student.StudentType?.Trim();
            var isAutoGenerated = IsAutoGeneratedType(Student.StudentType);
            var isExistingStudent = IsExistingStudentType(Student.StudentType);
            SelectedCourseCode = SelectedCourseCode?.Trim();

            if (string.IsNullOrWhiteSpace(SelectedCourseCode))
            {
                ModelState.AddModelError(nameof(SelectedCourseCode), "Pumili ng valid na kurso.");
            }
            else
            {
                await LoadSelectedCourseAsync();
                if (SelectedCourse is null)
                {
                    ModelState.AddModelError(nameof(SelectedCourseCode), "Hindi na available ang napiling kurso.");
                }
                else
                {
                    ApplySelectedCourse();
                }
            }

            if (Student.BirthDate == default || Student.BirthDate.Date > DateTime.Today)
            {
                ModelState.AddModelError(
                    "Student.BirthDate",
                    "Maglagay ng valid na birth date gamit ang tamang taon, buwan, at araw.");
            }

            if (PaymentReceipt is not null)
            {
                var receiptExtension = Path.GetExtension(PaymentReceipt.FileName);
                if (PaymentReceipt.Length == 0
                    || PaymentReceipt.Length > MaxUploadBytes
                    || !AllowedDocumentExtensions.Contains(receiptExtension))
                {
                    ModelState.AddModelError(
                        nameof(PaymentReceipt),
                        "Mag-upload ng PDF o image na hanggang 10 MB lamang para sa payment receipt.");
                }
            }

            if (!isAutoGenerated && !isExistingStudent)
            {
                ModelState.AddModelError(
                    "Student.StudentType",
                    "Pumili ng Freshman, Transferee, Regular, o Irregular.");
            }
            else if (isExistingStudent && string.IsNullOrWhiteSpace(Student.StudentNumber))
            {
                ModelState.AddModelError(
                    "Student.StudentNumber",
                    "Ilagay ang kasalukuyan mong student number.");
            }

            if (!ModelState.IsValid)
            {
                if (isAutoGenerated)
                {
                    Student.StudentNumber = await _studentNumberService.GenerateUniqueAsync(
                        HttpContext.RequestAborted);
                    ModelState.Remove("Student.StudentNumber");
                }

                ModelState.Remove("Student.Course");
                ModelState.Remove("Student.CourseCode");
                return Page();
            }

            if (isExistingStudent)
            {
                var duplicateNumberExists = await _dbContext.Students
                    .AsNoTracking()
                    .AnyAsync(
                        existing => existing.StudentNumber == Student.StudentNumber!.Trim(),
                        HttpContext.RequestAborted);

                if (duplicateNumberExists)
                {
                    ModelState.Remove("Student.StudentNumber");
                    ModelState.AddModelError(
                        "Student.StudentNumber",
                        "May existing student na gumagamit na ng student number na ito.");
                    return Page();
                }
            }

            string uploadsFolder = Path.Combine(_environment.ContentRootPath, "App_Data", "uploads");
            if (!Directory.Exists(uploadsFolder))
            {
                Directory.CreateDirectory(uploadsFolder);
            }

            if (PaymentReceipt is not null)
            {
                var extension = Path.GetExtension(PaymentReceipt.FileName).ToLowerInvariant();
                var uniqueFileName = $"PaymentReceipt_{Guid.NewGuid():N}{extension}";
                var filePath = Path.Combine(uploadsFolder, uniqueFileName);
                await using (var fileStream = new FileStream(
                    filePath,
                    FileMode.CreateNew,
                    FileAccess.Write,
                    FileShare.None,
                    bufferSize: 81920,
                    useAsync: true))
                {
                    await PaymentReceipt.CopyToAsync(fileStream, HttpContext.RequestAborted);
                }

                Student.PaymentReceiptPath = "/private-uploads/" + uniqueFileName;
            }

            // 1. Profile Picture
            if (ProfilePicture != null)
            {
                string uniqueFileName = Guid.NewGuid().ToString("N") + "_" + Path.GetFileName(ProfilePicture.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await ProfilePicture.CopyToAsync(fileStream);
                }
                Student.ProfilePicturePath = "/private-uploads/" + uniqueFileName;
            }

            // 2. PSA Birth Certificate
            if (PsaBirthCertificate != null)
            {
                string uniqueFileName = "PSA_" + Guid.NewGuid().ToString("N") + "_" + Path.GetFileName(PsaBirthCertificate.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await PsaBirthCertificate.CopyToAsync(fileStream);
                }
                Student.PsaBirthCertificatePath = "/private-uploads/" + uniqueFileName;
            }

            // 3. Form 138
            if (Form138 != null)
            {
                string uniqueFileName = "Form138_" + Guid.NewGuid().ToString("N") + "_" + Path.GetFileName(Form138.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await Form138.CopyToAsync(fileStream);
                }
                Student.Form138Path = "/private-uploads/" + uniqueFileName;
            }

            // 4. Form 137
            if (Form137 != null)
            {
                string uniqueFileName = "Form137_" + Guid.NewGuid().ToString("N") + "_" + Path.GetFileName(Form137.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await Form137.CopyToAsync(fileStream);
                }
                Student.Form137Path = "/private-uploads/" + uniqueFileName;
            }

            // 5. Good Moral
            if (GoodMoral != null)
            {
                string uniqueFileName = "GoodMoral_" + Guid.NewGuid().ToString("N") + "_" + Path.GetFileName(GoodMoral.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await GoodMoral.CopyToAsync(fileStream);
                }
                Student.GoodMoralPath = "/private-uploads/" + uniqueFileName;
            }

            // 6. TOR
            if (Tor != null)
            {
                string uniqueFileName = "TOR_" + Guid.NewGuid().ToString("N") + "_" + Path.GetFileName(Tor.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await Tor.CopyToAsync(fileStream);
                }
                Student.TorPath = "/private-uploads/" + uniqueFileName;
            }

            Student.Id = 0;
            Student.Status = "Pending";
            string assignedStudentNumber;
            if (isAutoGenerated)
            {
                assignedStudentNumber = await _studentNumberService.AddStudentWithUniqueNumberAsync(
                    Student,
                    HttpContext.RequestAborted);
            }
            else
            {
                var providedNumber = Student.StudentNumber!.Trim();
                if (!await _studentNumberService.AddStudentWithProvidedNumberAsync(
                        Student,
                        providedNumber,
                        HttpContext.RequestAborted))
                {
                    ModelState.Remove("Student.StudentNumber");
                    ModelState.AddModelError(
                        "Student.StudentNumber",
                        "May existing student na gumagamit na ng student number na ito.");
                    return Page();
                }

                assignedStudentNumber = providedNumber;
            }

            SuccessMessage = $"Enrollment application submitted successfully. Your student number is {assignedStudentNumber}.";
            return RedirectToPage();
        }

        private async Task LoadSelectedCourseAsync()
        {
            SelectedCourse = await _dbContext.Courses
                .AsNoTracking()
                .SingleOrDefaultAsync(
                    course => course.CourseCode.ToUpper() == SelectedCourseCode!.ToUpper(),
                    HttpContext.RequestAborted);
        }

        private void ApplySelectedCourse()
        {
            Student.CourseId = SelectedCourse!.Id;
            Student.CourseCode = SelectedCourse.CourseCode;
            Student.Course = SelectedCourse.CourseName;
            ModelState.Remove("Student.Course");
            ModelState.Remove("Student.CourseCode");
        }

        private static bool IsAutoGeneratedType(string? studentType)
        {
            return string.Equals(studentType, "Freshman", StringComparison.OrdinalIgnoreCase)
                || string.Equals(studentType, "Transferee", StringComparison.OrdinalIgnoreCase);
        }

        private static bool IsExistingStudentType(string? studentType)
        {
            return string.Equals(studentType, "Regular", StringComparison.OrdinalIgnoreCase)
                || string.Equals(studentType, "Irregular", StringComparison.OrdinalIgnoreCase);
        }
    }
}